[package]
name = "SSTables"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
rbtree = "0.2.0"
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.142"
serde_yaml = "0.9.34"
uuid = { version = "1.8", features = ["v4"] }
