[package]
name = "SSTables"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
rbtree = "0.2.0"
serde = {version="1.0.219", features=["derive"]}
uuid = { version = "1.8", features = ["v4"] }
